services:
  localstack:
    image: localstack/localstack
    platform: linux/arm64
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=dynamodb
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1

  redis:
    image: redis:latest
    platform: linux/arm64
    container_name: redis
    ports:
      - "6379:6379"
